### ISSUE TITLE
rolling release: tag of existing release not updated

### ISSUE THREAD

**Issue by nicovince** [nicovince/update-release#1]
For rolling release the tag is not updated with that step:
```yaml
      - name: release
        uses: nicovince/manage-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: written_interview.pdf
```
