### ISSUE TITLE
error on tag push

### ISSUE THREAD

**Issue by nicovince** [nicovince/update-release#2]
With the following step:
```yaml
name: Compile
on: [push]

jobs:
  compile:
    runs-on: ubuntu-20.04
    name: Compile and upload
    steps:
...
      - name: release
        uses: nicovince/manage-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: written_interview.pdf

```
I have the following errors
```
/home/runner/work/_actions/nicovince/manage-release/main/manage-release.sh --release-name refs/tags/application_20221125        --release   written_interview.pdf
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
POSITIONAL_ARGS=
RELEASE_NAME=refs/tags/application_20221125
TAG=refs/tags/application_20221125
SHA1=ec3f1a67f85522822b4b84c08ac252df180e1103
MESSAGE=refs/tags/application_20221125 latest release
BODY=refs/tags/application_20221125 latest release
PRERELEASE=0
DRAFT=0
github.com
  ✓ Logged in to github.com as github-actions[bot] (GITHUB_TOKEN)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: *******************
  
Found releases: main
Release refs/tags/application_20221125 does not exist
Create release refs/tags/application_20221125 on refs/tags/application_20221125 at ec3f1a67f85522822b4b84c08ac252df180e1103
https://github.com/nicovince/canonical_application/releases/tag/application_20221125
Upload assets to release tagged at refs/tags/application_20221125
release not found
```
